const R2 = 'https://pub-c3a151aad3544d4297431bb6fef7f945.r2.dev';
const BASE = import.meta.env.BASE_URL;

export const media = {
  hero: `${R2}/Atomberg%20Factory%20Edit_With%20Map%20Animation%20V2.mp4`,
  meet: `${R2}/Atomberg%20CPJ_TheBoredMonkey%20Studios.mp4`,
  workA: `${R2}/Biopeak%20Script%202.mp4`,
  workB: `${R2}/Blue%20Tyga_DVC_13.4.2026.mp4`,
  workC: `${R2}/CUSTOMER%20POV.mp4`,
  workD: `${R2}/Script%203_2%20min_Version_20%20Nov_1.mp4`,
  workE: `${R2}/Technician%20POV%20.mp4`,
  workF: `${R2}/Atomberg%20Podcast%20Teaser.mp4`,
};

export const content = {
  brand: 'SEQUENCE',
  ui: { menu: 'Menu', close: 'Close', copied: 'Copied', arrow: '↗', play: '▸', mark: '▥', registered: '®', plus: '+', minus: '−', videoLabel: 'Sequence studio video' },
  nav: [
    { index: '[01]', label: 'Home', href: '#home' },
    { index: '[02]', label: 'Works', href: '#works' },
    { index: '[03]', label: 'Gallery', href: '#gallery' },
    { index: '[04]', label: 'The Room', href: '#about' },
    { index: '[05]', label: 'Services', href: '#services' },
    { index: '[06]', label: 'Stats', href: '#stats' },
    { index: '[07]', label: 'Contact', href: '#contact' },
  ],
  hero: {
    play: 'PLAY SHOWREEL',
    year: '2026',
    title: 'We Make Videos People Remember',
    description: 'TheBoredMonkey is a creative production studio focused on crafting visual stories that move people. From concept to final delivery, we bring your vision to life.',
    viewWorks: 'VIEW WORKS',
    location: '[MUMBAI BASED]',
    agency: '[AWARD WINNING AGENCY]',
    established: '[EST 2022]',
    clock: '3:34:33 AM',
    slides: [
      { brand: 'ATOMBERG', product: 'Atomberg', video: `${R2}/Atomberg%20.mp4`, logo: `${BASE}/brands/Atomberg-logo.svg` },
      { brand: 'BIOPEAK', product: 'Biopeak', video: `${R2}/Biopeak.mp4`, logo: `${BASE}/brands/biopeak-logo-white.png` },
      { brand: 'BLUE TYGA', product: 'Blue Tyga', video: `${R2}/Blue%20Tyga.mp4`, logo: `${BASE}/brands/bluetyga-logo-white.png` },
      { brand: 'VIBHOR', product: 'Vibhor', video: `${R2}/Vibhor.mp4`, logo: `${BASE}/brands/vibhor-logo.png` },
      { brand: 'ZOFF', product: 'Zoff', video: `${R2}/Zoff.mp4`, logo: `${BASE}/brands/zoff-logo-white.png` },
    ],
  },
  meet: {
    title: 'Meet Sequence',
    files: ['SCENE_12.MP4', 'CLIP_004.MOV'],
    copy: "From concept development and filming to editing, animation, and final delivery, we help brands create content that connects with audiences and drives meaningful results.",
    cta: 'More ABout Us',
    stat: '8 YEARS 120+ BRANDS',
    statCopy: "Every logo here represents a creative partnership, a shared vision, and a project we're proud to put our name on.",
    catalog: 'Catalog',
    partners: ['CloudPeak', 'Convergence', 'Datanova', 'Command+R', 'Basil & Co.', 'Global Bank', 'VitaCare'],
  },
  works: {
    eyebrow: 'Featured Works',
    file: 'MASTER_EDIT.PRPROJ',
    title: "A Few Projects We're Proud Of",
    cta: 'Explore All Works',
    projects: [
      { year: '©2025', title: 'ATOMBERG CPJ', categories: ['Commercial', 'Brand Film'], media: media.meet },
      { year: '©2025', title: 'ATOMBERG FACTORY', categories: ['Corporate', 'Documentary'], media: media.hero },
      { year: '©2026', title: 'BIOPEAK SCRIPT', categories: ['Commercial', 'Product'], media: media.workA },
      { year: '©2026', title: 'BLUE TYGA', categories: ['Ad Film', 'Brand Film'], media: media.workB },
      { year: '©2026', title: 'CUSTOMER POV', categories: ['Testimonial', 'Social Media'], media: media.workC },
      { year: '©2026', title: 'SCRIPT 3', categories: ['Commercial', 'Short Film'], media: media.workD },
      { year: '©2026', title: 'TECHNICIAN POV', categories: ['Documentary', 'Corporate'], media: media.workE },
      { year: '©2026', title: 'PODCAST TEASER', categories: ['Podcast', 'Social Media'], media: media.workF },
    ],
  },
  services: {
    eyebrow: 'What We Make',
    file: 'A_CAM_012.MXF',
    title: 'Built around the entire production process.',
    items: [
      { number: '[001]', title: 'Video production', copy: 'From the first shot to the final scene, we handle every step of production with creativity, precision, and attention to detail, delivering high quality videos that bring your ideas to life.', price: 'Starting at $1,500', details: ['Typical delivery:', '2–6 weeks', 'Pre-production included', '4K filming available'], categories: ['Commercial Video Production', 'Corporate Videos', 'Product Videos', 'Event Videography', 'Documentary Production', 'Interview & Testimonial Videos', 'Real Estate Videography', 'Advertise', 'Raw Video'] },
      { number: '[002]', title: 'Video editing', copy: 'Every great video is shaped in the edit. We transform raw footage into polished, engaging content with seamless cuts, smooth pacing, and professional finishing touches that keep every second working harder.', price: 'Starting at $99', details: ['2–5 business days', '1 free revision included', '4K export available'], categories: ['Short Form Video', 'Long Form Video', 'YouTube Video', 'Podcast Video', 'Corporate Video', 'Educational Video', 'Product Video', 'Interview Video', 'Social Media Video'] },
      { number: '[003]', title: 'Motion graphics', copy: 'Bring static ideas to life with eye catching motion, smooth animations, and dynamic visuals that help your brand stand out across every screen and every platform.', price: 'Starting at $399', details: ['5–10 business days', 'Custom animations from scratch'], categories: ['2D Animation', '3D Animation', 'Logo Animation', 'Kinetic Typography', 'UI & App Animation', 'Product Animation', 'Animated Infographics', 'Explainer Videos'] },
      { number: '[004]', title: 'Post production', copy: 'The finishing touches that make all the difference. We refine every detail to deliver polished, cinematic videos that sound better, look sharper, and are ready for any screen.', price: 'Starting at $249', details: ['3–7 business days'], categories: ['Color Grading', 'Color Correction', 'Sound Design', 'Audio Mixing', 'Audio Cleanup', 'Visual Effects (VFX)', 'Video Restoration', 'Subtitle & Captioning', 'Final Mastering'] },
      { number: '[005]', title: 'Content creation', copy: 'Create content that stops the scroll and starts conversations. From product launches to everyday brand moments, we produce platform ready content designed to connect with your audience and keep them coming back.', price: 'Starting at $299', details: ['3–5 business days', 'Optimized for every platform'], categories: ['UGC Content', 'Social Media Content', 'Brand Content', 'Product Content', 'Educational Content', 'Lifestyle Content', 'Promotional Content', 'YouTube Content', 'Short Form Content'] },
    ],
  },
  expertise: {
    eyebrow: 'OUR EXPERTISE',
    file: 'COLOR_PASS.MOV',
    title: 'Different Businesses. Same Creative Obsession.',
    copy: 'We partner with brands across diverse industries, delivering creative video solutions designed to engage, inspire, and make a lasting impact.',
  },
  ourServices: {
    eyebrow: '08',
    title: 'Our Services',
    intro: 'We are a digital studio based in Mumbai, focused on crafting visual stories that move people.',
    subtitle: 'From concept development to final delivery, we bring your vision to life with precision and creativity.',
    features: ['Convert More, Grow Faster', 'Future-Proof & Scalable'],
    cta: 'View about',
    items: [
      { name: 'Professional Videography', category: 'Production', media: media.workA, dots: 2 },
      { name: 'Branded Content', category: 'Marketing', media: media.workB, dots: 3 },
      { name: 'Vertical Ad Films', category: 'Advertising', media: media.workC, dots: 3 },
      { name: 'Product Launch Videos', category: 'Commercial', media: media.workD, dots: 4 },
    ],
  },
  trustedBy: {
    eyebrow: 'Trusted By',
    title: 'Crafted for 15+ Brands',
    copy: 'Every logo here represents a creative partnership, a shared vision, and a project we\'re proud to put our name on.',
    logos: [
      { name: 'Atomberg', src: `${BASE}/brands/Atomberg.jpg` },
      { name: 'Biopeak', src: `${BASE}/brands/Biopeak.png` },
      { name: 'Blue Tyga', src: `${BASE}/brands/Blue Tyga.png` },
      { name: 'CheQ', src: `${BASE}/brands/CheQ.jpg` },
      { name: 'Eat Anytime', src: `${BASE}/brands/eatanytime_new_logo.avif` },
      { name: 'Eclipse Solaire', src: `${BASE}/brands/eclipse solaire.jpg` },
      { name: 'Zoff', src: `${BASE}/brands/ZOFF Logo 2195.png` },
      { name: 'Wakefit', src: `${BASE}/brands/wakefit.png` },
      { name: 'Reequil', src: `${BASE}/brands/REEQUIL_logo.png` },
      { name: 'Pilgrim', src: `${BASE}/brands/Pilgrim-New-Logo-Without-Tagline_a9de71c3-9c1c-4a33-b4eb-95830dab01db.avif` },
      { name: 'Rabitat', src: `${BASE}/brands/Rabitat.webp` },
      { name: 'Neemans', src: `${BASE}/brands/Neemans-Lakeshore-Y-Junction-Hyderabad.webp` },
      { name: 'Rorosaur', src: `${BASE}/brands/Rorosaur_logo_1_1.avif` },
    ],
  },
  stats: {
    eyebrow: 'Studio',
    introParts: [
      { text: 'Founded in 2020, TheBoredMonkey Studios is the production and post-production wing of TheBoredMonkey.' },
      { text: 'We work with ', highlight: true },
      { text: '"WHATEVER IT TAKES MINDSET."', highlight: true },
      { text: ' Full pipeline in-house. One team, one brief, one standard, from the first creative conversation to final delivery.' },
    ],
    items: [
      { number: '6', label: 'Years Creating', copy: 'Helping brands tell better stories through thoughtful video production and creative post production.' },
      { number: '1500+', label: 'Videos Delivered', copy: 'From short form content to brand films, every project is crafted with purpose and precision.' },
      { number: '15', label: 'Creative Partners', copy: 'Long term collaborations built on trust, creativity, and consistent results.' },
      { number: '78', label: '% Repeat Clients', copy: 'Many of our clients return with new ideas, new campaigns, and bigger ambitions.' },
    ],
  },
  testimonials: {
    eyebrow: 'Nice Things, Unscripted',
    file: 'TAKE_08.MOV',
    title: 'They Said It Better Than We Could',
    copy: 'Honest notes from clients who survived the process, loved the result, and were kind enough to put it in writing.',
    rating: '4.9',
    ratingSuffix: '/5',
    ratingLabel: 'Average Rating from 480+ Verified Reviews',
    platforms: ['200+ Clutch Reviews', '200+ Facebook Reviews', '20+ Trustpilot Reviews', '80+ Google Reviews'],
    quotes: [
      { name: 'Ephram Vale', role: 'Creative Director, Marlowe & Finch', quote: '“The quality speaks for itself.”' },
      { name: 'Bastian Crowe', role: 'Brand Lead, Elmora Goods', quote: '“As a growing company, finding a creative partner we could trust was incredibly important. This team made the process simple from day one. They listened carefully, communicated clearly, and delivered work that felt polished without losing our brand’s personality.”' },
      { name: 'Leander Knox', role: 'Co-Founder, Cedarline Supply', quote: '“Fast, creative, and incredibly easy to work with.”' },
      { name: 'Torin Ashford', role: 'Founder, Brightseed Studio', quote: '' },
      { name: 'Oswin Calder', role: 'Marketing Director, Vireo Labs', quote: '“You absolutely nailed it.”' },
      { name: 'Ivor Selwyn', role: 'Owner, Haven & Hearth', quote: '' },
    ],
  },
  packages: {
    eyebrow: 'Pick Your Production',
    file: 'SHOT_021.MOV',
    title: 'Choose the Right Production for What You’re Making',
    copy: 'These are practical starting points based on real production scope—not mysterious numbers pulled from a stylish hat. We’ll confirm the final quote after a short call, and if your project sits between packages, we’ll shape a sensible middle ground.',
    plans: [
      { name: 'First Take', description: 'Perfect for startups and small businesses looking for professional video production.', pricePrefix: 'From', price: '$1,500', cta: 'PLAN A QUICK CUT', includedTitle: 'Included in First Take:', included: ['Half Day Production', 'Creative Planning', 'Professional Editing', 'Color grade + sound mix', 'Two feedback rounds', '4K masters + web exports'] },
      { name: "Director's Cut", description: 'A tailored solution for ambitious productions that deserve the full creative treatment.', pricePrefix: '', price: '$4,800', cta: "Let's Plan IT", includedTitle: "Included in Director's Cut:", included: ['Creative concept', 'Multi Day Production', 'Dedicated Production Crew', 'Dialogue cleanup', 'Sound design', 'Three feedback rounds', 'Multi-format 4K exports', 'Unlimited Consultation'] },
    ],
  },
  faq: {
    eyebrow: 'Questions, Meet Answers',
    file: 'FINAL_EXPORT.MP4',
    title: 'The Questions Before the Cameras Roll',
    items: [
      { question: 'What kind of videos can you create for us?', answer: ['Formats shaped around your brief', 'End-to-end support:', 'concept through final delivery', 'Filming, editing, motion, and finishing available', 'Platform-ready masters and cutdowns'] },
      { question: 'How does the whole production process work?', answer: ['Discovery and creative direction', 'Pre-production:', 'script, schedule, crew, and locations', 'Production with a clear, calm plan', 'Editing, feedback, finishing, and delivery'] },
      { question: 'What if we only have a rough idea?', answer: ['A polished brief is not required', 'We help define:', 'message, audience, format, and tone', 'Clear references and scope before production', 'Honest recommendations without the jargon parade'] },
      { question: 'How long will our project take, and how do revisions work?', answer: ['Short-form and focused edits: often 1–3 weeks', 'Larger productions:', 'commonly 4–8+ weeks', 'Revision rounds are agreed before kickoff', 'Consolidated feedback keeps everything moving'] },
      { question: 'How much does a project cost, and what is included?', answer: ['A clear, itemized proposal before kickoff', 'Delivery options:', '16:9, 1:1, 4:5, and 9:16', 'Cutdowns, captions, hooks, and thumbnails available', 'Optional extras are approved before work begins'] },
      { question: 'Can you work remotely, travel, or collaborate with our in-house team?', answer: ['Remote planning and reviews work beautifully', 'On-location production:', 'travel can be scoped when needed', 'Flexible collaboration with your internal team', 'Roles and approvals are clear before kickoff'] },
      { question: 'What do you need from us before the project starts?', answer: ['Goals, audience, timing, and budget context', 'Brand assets, references, and must-avoid notes', 'Access to products, people, and locations', 'One clear approval path keeps things speedy'] },
      { question: 'What if our team feels awkward on camera?', answer: ['Conversational prompts instead of rigid speeches', 'A calm set with a right-sized crew', 'Teleprompter, voiceover, and hands-only options', 'The edit brings together the strongest moments'] },
      { question: 'Who owns the final video, and how are usage rights handled?', answer: ['Usage and ownership are written into the proposal', 'Third-party licenses are documented clearly', 'Raw-footage terms are agreed in advance', 'No fine-print treasure hunt at delivery'] },
      { question: 'What happens after the final video is delivered?', answer: ['Organized, clearly named delivery folders', 'Platform cutdowns, captions, and thumbnails available', 'Archive timing is confirmed at handoff', 'Future campaign versions can grow from the master'] },
    ],
  },
  insights: {
    eyebrow: 'Fresh IDeas',
    title: 'Fresh Perspectives from the Studio',
    copy: 'Production lessons, creative experiments, and practical ideas from people who spend a suspicious amount of time inside timelines.',
    cta: 'READ ALL BLOGS',
    posts: [
      { date: '10', month: 'Jul 2026', category: 'Production', title: 'The Calm Shoot-Day Playbook for Happier Crews and Better Footage', media: media.workA },
      { date: '12', month: 'Jun 2026', category: '', title: 'Interview Lighting That Still Feels Human, Warm, and Believable', media: media.workB },
      { date: '', month: '', category: 'Post Production', title: 'Edit Notes That Do Not Make Editors Guess What You Really Mean', media: media.workC },
    ],
  },
  contact: {
    eyebrow: 'Contact Now',
    title: 'Contact Us!',
    subtitle: "Let's create something amazing together! Reach out, I'd love to hear about your project and ideas.",
    features: ['24/7 Full Time Support', 'Available Worldwide'],
    cta: 'Contact now',
    email: 'monu@theboredmonkey.com',
    phone: '9004254057',
    calendarLink: '#',
  },
  footer: {
    socials: [
      { label: 'Instagram', href: '#' },
      { label: 'LinkedIn', href: '#' },
      { label: 'Twitter', href: '#' },
      { label: 'Facebook', href: '#' },
    ],
    address: '22, 2nd Floor, Kamat Industrial Estate, Opp Siddhivinayak Mandir, Veer Savarkar, Maharashtra 400025',
    phone: '+91 7208477288',
    email: 'monu@theboredmonkey.com',
    businessLabel: 'For business:',
    businessEmail: 'bd@theboredmonkey.com',
    careersLabel: 'To join our team:',
    careersEmail: 'careers@theboredmonkey.com',
    agencyLabel: 'For creator or agency:',
    agencyEmail: 'Connect@theboredmonkey.com',
  },
  gallery: {
    eyebrow: 'Selected Works',
    file: 'TIMELINE_01.PPROJ',
    title: 'Our Best Work',
    cta: 'See All',
    categories: [
      {
        label: 'DVCs',
        film: { brand: 'Blue Tyga', type: 'DVC', concept: 'Made for comfort, built for impact', credit: 'Produced by TheBoredMonkey', media: media.workB, logo: `${BASE}/brands/Blue Tyga.png` },
      },
      {
        label: 'Vertical ad films',
        film: { brand: 'Atomberg', type: 'Vertical Ad Film', concept: 'Fan technology that speaks for itself', credit: 'Produced by TheBoredMonkey', media: media.workD, logo: `${BASE}/brands/Atomberg.jpg` },
      },
      {
        label: 'Product launch videos',
        film: { brand: 'Atomberg', type: 'Product Launch', concept: 'Introducing the next gen water purifier', credit: 'Produced by TheBoredMonkey', media: media.meet, logo: `${BASE}/brands/Atomberg.jpg` },
      },
      {
        label: 'Factory',
        film: { brand: 'Atomberg', type: 'Factory Film', concept: 'Inside the making of innovation', credit: 'Produced by TheBoredMonkey', media: media.hero, logo: `${BASE}/brands/Atomberg.jpg` },
      },
      {
        label: 'Founder',
        film: { brand: 'TheBoredMonkey', type: 'Founder Film', concept: 'The story behind the studio', credit: 'Directed by TheBoredMonkey', media: media.workC, logo: `/logo.png` },
      },
      {
        label: 'Podcast',
        film: { brand: 'Atomberg', type: 'Podcast Teaser', concept: 'Conversations that drive innovation', credit: 'Produced by TheBoredMonkey', media: media.workF, logo: `${BASE}/brands/Atomberg.jpg` },
      },
      {
        label: 'Long-form',
        film: { brand: 'Biopeak', type: 'Long-form Film', concept: 'Wellness, redefined from the ground up', credit: 'Produced by TheBoredMonkey', media: media.workA, logo: `${BASE}/brands/Biopeak.png` },
      },
    ],
    films: [
      { brand: 'CloudPeak', type: 'Ad Film', concept: 'Where ambition meets altitude', credit: 'Produced by Sequence', media: media.workA, vertical: false },
      { brand: 'VitaCare', type: 'Brand Film', concept: 'Wellness, redefined for a new generation', credit: 'Produced by Sequence', media: media.workB, vertical: true },
      { brand: 'Global Bank', type: 'Product Film', concept: 'Trust built into every transaction', credit: 'Directed by Arlo Voss', media: media.workC, vertical: false },
      { brand: 'Convergence', type: 'Vertical Ad Film', concept: 'Ideas that move faster', credit: 'Produced by Sequence', media: media.workD, vertical: true },
      { brand: 'Datanova', type: 'Brand Film', concept: 'Data without the noise', credit: 'Directed by Mira Chen', media: media.meet, vertical: false },
      { brand: 'Basil & Co.', type: 'Ad Film', concept: 'Craft you can taste', credit: 'Produced by Sequence', media: media.workA, vertical: false },
      { brand: 'Command+R', type: 'Vertical Ad Film', concept: 'Restart your creative workflow', credit: 'Directed by Arlo Voss', media: media.workB, vertical: true },
    ],
  },
  brandGrid: {
    eyebrow: 'Selected Works',
    file: 'TAKE_12.MOV',
    title: 'Behind Every Frame',
    films: [
      { brand: 'MIRA LENS', type: 'Ad Film', concept: 'Light that tells a story', credit: 'Produced by Sequence', media: media.workA, height: 'tall' as const },
      { brand: 'AKOYA', type: 'Vertical Ad Film', concept: 'Silence, then presence', credit: 'Directed by Mira Chen', media: media.workB, height: 'tall' as const },
      { brand: 'AFTERIMAGE', type: 'Brand Film', concept: 'Afterimage', credit: 'Directed by Arlo Voss', media: media.workC, height: 'mid' as const },
      { brand: 'VELVET ROOM', type: 'Product Film', concept: 'Softness, framed with precision', credit: 'Produced by Sequence', media: media.workD, height: 'mid' as const },
      { brand: 'NEON DRIFT', type: 'Ad Film', concept: 'Motion through the city lights', credit: 'Directed by Arlo Voss', media: media.meet, height: 'tall' as const },
      { brand: 'EMBER & ASH', type: 'Brand Film', concept: 'Where fire meets memory', credit: 'Produced by Sequence', media: media.hero, height: 'mid' as const },
      { brand: 'LUMEN', type: 'Product Film', concept: 'Clarity in every shutter', credit: 'Directed by Mira Chen', media: media.workC, height: 'short' as const },
      { brand: 'NORD', type: 'Ad Film', concept: 'Silence and shadow', credit: 'Produced by Sequence', media: media.workB, height: 'short' as const },
      { brand: 'HUSH', type: 'Vertical Ad Film', concept: 'A whisper on screen', credit: 'Directed by Arlo Voss', media: media.workA, height: 'mid' as const },
    ],
  },
  brandShowcase: {
    headerTitle: 'One approach\nEndless possibilities.',
    headerSub: 'We partner with forward-thinking teams and ambitious brands to build digital experiences that creates impact.',
    projects: [
      { brand: 'ROWAN & CO.', type: 'Brand Film', concept: 'Clarity, culture, and timeless design', credit: 'Produced by Sequence', context: 'Independent identities for brands that value substance over noise.', media: media.workA },
      { brand: 'SYNTH', type: 'Product Film', concept: 'Generative intelligence, made human', credit: 'Directed by Mira Chen', context: 'Tools that feel intuitive because they were built with the user in mind.', media: media.workB },
      { brand: 'ARC ONE', type: 'Ad Film', concept: 'Distilled form, tactile material', credit: 'Produced by Sequence', context: 'A single gesture that says everything.', media: media.workC },
    ],
  },
  theRoom: {
    eyebrow: '07',
    title: 'Filmmakers / The Room',
    members: [
      {
        name: 'Mira Chen',
        role: 'Director & Cinematographer',
        brands: ['MIRA LENS', 'LUMEN', 'HUSH', 'ROWAN & CO.', 'SYNTH'],
        image: `${R2}/Atomberg%20CPJ_TheBoredMonkey%20Studios.mp4`,
      },
      {
        name: 'Arlo Voss',
        role: 'Creative Director',
        brands: ['AFTERIMAGE', 'NEON DRIFT', 'NORD', 'EMBER & ASH', 'ARC ONE'],
        image: `${R2}/Atomberg%20Factory%20Edit_With%20Map%20Animation%20V2.mp4`,
      },
      {
        name: 'Kai Rivera',
        role: 'Editor & Colorist',
        brands: ['VELVET ROOM', 'AKOYA', 'LUMEN', 'SYNTH', 'HUSH'],
        image: `${R2}/Biopeak%20Script%202.mp4`,
      },
      {
        name: 'Suki Tanaka',
        role: 'Motion Designer',
        brands: ['MIRA LENS', 'AFTERIMAGE', 'NORD', 'ROWAN & CO.', 'NEON DRIFT'],
        image: `${R2}/Blue%20Tyga_DVC_13.4.2026.mp4`,
      },
    ],
  },
} as const;